/**
 * AGENTS.md Generator (#1270)
 *
 * Emits a tool-agnostic `AGENTS.md` at the repo root — the neutral, cross-tool
 * agent-configuration convention adopted across the 2026 ecosystem (Cursor,
 * Kiro, most SDD tools). `CLAUDE.md` stays canonical for Claude Code; AGENTS.md
 * is a generated *interop view* of the same moflo conventions so a repo touched
 * by multiple agents carries one neutral contract they all read.
 *
 * Relationship to claudemd-generator.ts:
 *   - Both project the same moflo conventions, but AGENTS.md is deliberately
 *     tool-neutral (CLI-forward: `flo-search`, `flo`) rather than Claude-specific
 *     (`mcp__moflo__*`). They are separate outputs on purpose — one canonical,
 *     one interop — not a shared string.
 *   - This module is self-contained: its own marker pair and its own tiny
 *     inject/drift helpers, so it never broadens the launcher-critical,
 *     zero-import `services/claudemd-injection.ts`. The logic mirrors that
 *     module's create/replace/append semantics.
 *
 * Merge safety: the moflo block lives between markers. A user's own content
 * outside the markers is always preserved; re-running only rewrites the block.
 */

import * as fs from 'fs';
import * as path from 'path';

export const AGENTS_MARKER_START = '<!-- MOFLO:AGENTS:START -->';
export const AGENTS_MARKER_END = '<!-- MOFLO:AGENTS:END -->';

/**
 * The moflo block projected into AGENTS.md. Built from a line array (not a
 * template literal) so the embedded ``` code fences and inline `code` need no
 * backtick escaping — the escaping trap that breaks template-literal builds.
 * ~28 lines; points to the shipped guidance for everything else.
 */
function mofloBlock(): string {
  const lines = [
    AGENTS_MARKER_START,
    '## MoFlo — Agent Orchestration (tool-agnostic)',
    '',
    'This repository uses **moflo** for AI-agent orchestration. `AGENTS.md` is the',
    'neutral, cross-tool contract that agents read; `CLAUDE.md` stays canonical for',
    'Claude Code. This block is generated by moflo — edits **inside** the markers are',
    'overwritten on the next `flo init`. Add your own content **outside** the markers',
    'and it is preserved.',
    '',
    '### Search memory before you edit',
    '',
    'This project ships a semantic index of its code, tests, and guidance. Before',
    'changing code, search it from any tool that can run a shell command:',
    '',
    '```',
    'flo-search "<symbol or keyword>"',
    '```',
    '',
    'Pivot on the bare symbol or keyword, not a natural-language question.',
    '',
    '### Workflow expectations',
    '',
    '- Run the project tests before proposing a change; never open a PR on red.',
    '- Keep changes cross-platform (Linux, macOS, Windows): no hardcoded path',
    '  separators, no shelling out to tools absent on Windows.',
    '- Prefer existing helpers over re-implementing — the memory search above',
    '  surfaces them.',
    '',
    '### Reference',
    '',
    '- Using moflo (CLI, hooks, config): `.claude/guidance/moflo-core-guidance.md`',
    '- Universal agent rules (memory, git/PR, file org): `.claude/guidance/moflo-agent-rules.md`',
    '',
    '_Generated by moflo. Regenerate with `flo init` or `flo init upgrade`._',
    AGENTS_MARKER_END,
  ];
  return lines.join('\n');
}

/**
 * Generate the canonical AGENTS.md content (moflo block + trailing newline).
 * Optional args are accepted and ignored so callers from the dev tree (TS) and
 * any plain-JS caller can invoke `generateAgentsMd()` / `generateAgentsMd({})`
 * interchangeably — mirrors `generateClaudeMd`.
 */
export function generateAgentsMd(_options?: unknown): string {
  return mofloBlock() + '\n';
}

export type AgentsMdDriftState = 'no-file' | 'no-marker' | 'in-sync' | 'drifted';

/**
 * Locate the moflo block in existing AGENTS.md contents, normalising CRLF so a
 * Windows checkout (git autocrlf) matches the LF canonical block. Returns the
 * matched block plus its offsets in the normalised view, or null when absent.
 */
export function extractAgentsBlock(
  contents: string | null | undefined,
): { block: string; start: number; end: number } | null {
  if (!contents) return null;
  const normalised = contents.replace(/\r\n/g, '\n');
  const startIdx = normalised.indexOf(AGENTS_MARKER_START);
  if (startIdx < 0) return null;
  const endIdx = normalised.indexOf(AGENTS_MARKER_END, startIdx + AGENTS_MARKER_START.length);
  if (endIdx <= startIdx) return null;
  const endInclusive = endIdx + AGENTS_MARKER_END.length;
  return { block: normalised.substring(startIdx, endInclusive), start: startIdx, end: endInclusive };
}

/** Trim the canonical string to the exact bytes between (and including) markers. */
function canonicalBlock(canonical: string): string {
  return canonical.replace(/\r\n/g, '\n').trimEnd();
}

/**
 * Classify existing AGENTS.md contents against the canonical block.
 * null/undefined ⇒ 'no-file'.
 */
export function computeAgentsMdDrift(
  contents: string | null | undefined,
  canonical: string,
): AgentsMdDriftState {
  if (contents === null || contents === undefined) return 'no-file';
  const extracted = extractAgentsBlock(contents);
  if (!extracted) return 'no-marker';
  return extracted.block === canonicalBlock(canonical) ? 'in-sync' : 'drifted';
}

export interface AgentsMdInjectionResult {
  /** Updated contents, or null when nothing should be written. */
  contents: string | null;
  /** True when `contents` differs from the input. */
  changed: boolean;
}

/**
 * Apply the canonical block to existing AGENTS.md contents. Pure — no I/O.
 *   - no-file  → fresh file with a title + block
 *   - no-marker→ APPEND the block (preserves the user's hand-authored file)
 *   - drifted  → REPLACE the block in place
 *   - in-sync  → no change
 * Output keeps LF endings, matching how init and the launcher write files.
 */
export function applyAgentsMdInjection(
  contents: string | null | undefined,
  canonical: string,
): AgentsMdInjectionResult {
  const want = canonicalBlock(canonical);

  if (contents === null || contents === undefined) {
    return { contents: `# Agent Configuration\n\n${want}\n`, changed: true };
  }

  const extracted = extractAgentsBlock(contents);
  if (!extracted) {
    const sep = contents.endsWith('\n') ? '\n' : '\n\n';
    return { contents: contents + sep + want + '\n', changed: true };
  }

  if (extracted.block === want) {
    return { contents, changed: false };
  }

  // Splice against the ORIGINAL contents (not the CRLF-normalised view used for
  // drift detection) so a Windows-checked-out file keeps its line endings and
  // byte content OUTSIDE the marker block untouched — only the moflo block is
  // rewritten. Markers are CR-free ASCII, so indexOf locates them identically
  // in either view. (The normalised offsets on `extracted` are correct only for
  // an all-LF file; using them here would rewrite the whole file's EOLs.)
  const origStart = contents.indexOf(AGENTS_MARKER_START);
  const origEnd = contents.indexOf(AGENTS_MARKER_END, origStart + AGENTS_MARKER_START.length) + AGENTS_MARKER_END.length;
  const next = contents.slice(0, origStart) + want + contents.slice(origEnd);
  return { contents: next, changed: true };
}

export interface WriteAgentsMdResult {
  status: 'created' | 'updated' | 'unchanged' | 'skipped';
  detail: string;
}

/**
 * Create or refresh `<root>/AGENTS.md`. Callers resolve the opt-out toggle
 * (`agents_md.enabled` in moflo.yaml) and pass `enabled`; when false this is a
 * no-op that reports 'skipped'. Cross-platform: joins with `path.join`, writes
 * LF, and never clobbers content outside the markers.
 */
export function writeAgentsMd(root: string, enabled: boolean): WriteAgentsMdResult {
  if (!enabled) {
    return { status: 'skipped', detail: 'agents_md.enabled: false' };
  }
  const agentsMdPath = path.join(root, 'AGENTS.md');
  const existed = fs.existsSync(agentsMdPath);
  const existing = existed ? fs.readFileSync(agentsMdPath, 'utf-8') : null;

  const result = applyAgentsMdInjection(existing, generateAgentsMd());
  if (result.contents !== null && (result.changed || !existed)) {
    fs.writeFileSync(agentsMdPath, result.contents, 'utf-8');
  }

  if (!existed) return { status: 'created', detail: 'AGENTS.md written (interop view)' };
  if (result.changed) return { status: 'updated', detail: 'AGENTS.md moflo block refreshed' };
  return { status: 'unchanged', detail: 'AGENTS.md already in sync' };
}

export default generateAgentsMd;
