#!/usr/bin/env node
'use strict';
var childProcess = require('child_process');

var PROJECT_DIR = (process.env.CLAUDE_PROJECT_DIR || process.cwd()).replace(/^\/([a-z])\//i, '$1:/');

try {
  var hash = childProcess.execFileSync('git', ['rev-parse', 'HEAD'], {
    encoding: 'utf-8',
    cwd: PROJECT_DIR,
    windowsHide: true
  }).trim();

  var msg = childProcess.execFileSync('git', ['log', '-1', '--pretty=%B'], {
    encoding: 'utf-8',
    cwd: PROJECT_DIR,
    windowsHide: true
  }).trim();

  console.log('Commit recorded: ' + hash.substring(0, 8));
} catch (e) {
  // Non-fatal
}
