#!/usr/bin/env node
/**
 * MoFlo Project Setup
 *
 * Copies the subagents guidance into the consuming project and
 * adds a CLAUDE.md section so subagents automatically follow the protocol.
 *
 * Usage:
 *   flo-setup            # First-time setup
 *   flo-setup --update   # Refresh bootstrap file after moflo upgrade
 *   flo-setup --check    # Check if setup is current
 *
 * What it does:
 *   1. Copies moflo/.claude/guidance/shipped/moflo-subagents.md → project's .claude/guidance/moflo-bootstrap.md
 *   2. Appends a subagent protocol section to CLAUDE.md (idempotent, with markers)
 *
 * The project can layer its own guidance files on top for
 * project-specific rules (companyId, entity templates, etc.).
 *
 * The CLAUDE.md content is owned by `src/cli/init/claudemd-generator.ts` (compiled to
 * `dist/src/cli/init/claudemd-generator.js`). This script is a thin wrapper so consumers
 * always get byte-identical output regardless of which entry point they use
 * (`flo init` vs `flo-setup`).
 */

import { existsSync, readFileSync, writeFileSync, mkdirSync, copyFileSync } from 'node:fs';
import { dirname, resolve, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { mofloInternalURL } from './lib/moflo-resolve.mjs';

// Resolve moflo's installed package root via Node module resolution so the script
// works identically from bin/ (canonical) or from .claude/scripts/ (synced copy).
const mofloRoot = dirname(fileURLToPath(mofloInternalURL('package.json')));

// Single source of truth: claudemd-generator.ts owns the section content.
// Use the shared mofloInternalURL helper so the script works identically when
// invoked from bin/ (canonical) or from .claude/scripts/ (synced copy).
const {
  generateClaudeMd,
  MARKER_START,
  MARKER_END,
  LEGACY_MARKER_STARTS,
  LEGACY_MARKER_ENDS,
} = await import(mofloInternalURL('dist/src/cli/init/claudemd-generator.js'));

const args = process.argv.slice(2);
const updateOnly = args.includes('--update');
const checkOnly = args.includes('--check');

// Canonical section content (owned by claudemd-generator.ts). Trim the trailing newline
// that generateClaudeMd appends so the marker-replace logic below stays exact.
const CLAUDE_MD_SECTION = generateClaudeMd({}).trimEnd();

function log(msg) {
  console.log(`[flo-setup] ${msg}`);
}

function findProjectRoot() {
  // Walk up from cwd looking for package.json that depends on moflo
  let dir = process.cwd();
  const root = resolve(dir, '/');

  while (dir !== root) {
    const pkgPath = join(dir, 'package.json');
    if (existsSync(pkgPath)) {
      try {
        const pkg = JSON.parse(readFileSync(pkgPath, 'utf-8'));
        const deps = { ...pkg.dependencies, ...pkg.devDependencies };
        if (deps && deps.moflo) {
          return dir;
        }
      } catch { /* ignore parse errors */ }
    }
    dir = dirname(dir);
  }

  // Fallback: use cwd if it has a package.json
  if (existsSync(join(process.cwd(), 'package.json'))) {
    return process.cwd();
  }

  return null;
}

function copyBootstrap(projectRoot) {
  const shippedSource = join(mofloRoot, '.claude', 'guidance', 'shipped', 'moflo-subagents.md');
  const source = existsSync(shippedSource)
    ? shippedSource
    : join(mofloRoot, '.claude', 'guidance', 'moflo-subagents.md');
  const targetDir = join(projectRoot, '.claude', 'guidance');
  const target = join(targetDir, 'moflo-bootstrap.md');

  if (!existsSync(source)) {
    log('❌ Source bootstrap not found in moflo package');
    return false;
  }

  // Read source content and prepend auto-generated notice
  const content = readFileSync(source, 'utf-8');
  const header = `<!-- AUTO-GENERATED by flo-setup. Do not edit — changes will be overwritten. -->
<!-- Source: node_modules/moflo/.claude/guidance/shipped/moflo-subagents.md -->
<!-- To customize, add project-specific guidance in .claude/guidance/. -->

`;

  mkdirSync(targetDir, { recursive: true });

  // Check if file exists and is current
  if (existsSync(target)) {
    const existing = readFileSync(target, 'utf-8');
    const newContent = header + content;
    if (existing === newContent) {
      log('✅ moflo-bootstrap.md is current');
      return true;
    }
    log('📝 Updating moflo-bootstrap.md');
  } else {
    log('📝 Creating .claude/guidance/moflo-bootstrap.md');
  }

  if (!checkOnly) {
    writeFileSync(target, header + content, 'utf-8');
  }
  return true;
}

function updateClaudeMd(projectRoot) {
  const claudeMdPath = join(projectRoot, 'CLAUDE.md');

  if (!existsSync(claudeMdPath)) {
    if (checkOnly) {
      log('⚠️  No CLAUDE.md found');
      return false;
    }
    log('📝 Creating CLAUDE.md with subagent protocol section');
    writeFileSync(claudeMdPath, `# Project Configuration\n\n${CLAUDE_MD_SECTION}\n`, 'utf-8');
    return true;
  }

  const content = readFileSync(claudeMdPath, 'utf-8');

  // Check for current or legacy markers and replace
  const allStarts = [MARKER_START, ...LEGACY_MARKER_STARTS];
  const allEnds = [MARKER_END, ...LEGACY_MARKER_ENDS];

  for (let i = 0; i < allStarts.length; i++) {
    if (content.includes(allStarts[i])) {
      const startIdx = content.indexOf(allStarts[i]);
      const endIdx = content.indexOf(allEnds[i]);

      if (endIdx > startIdx) {
        // If current markers and content matches, we're up to date
        if (i === 0) {
          const existingSection = content.substring(startIdx, endIdx + allEnds[i].length);
          if (existingSection === CLAUDE_MD_SECTION) {
            log('✅ CLAUDE.md moflo section is current');
            return true;
          }
        }

        // Replace (current or legacy) with new section
        if (!checkOnly) {
          const updated = content.substring(0, startIdx) + CLAUDE_MD_SECTION + content.substring(endIdx + allEnds[i].length);
          writeFileSync(claudeMdPath, updated, 'utf-8');
          log(i === 0 ? '📝 Updated CLAUDE.md moflo section' : '📝 Replaced legacy CLAUDE.md section with minimal moflo injection');
        } else {
          log('⚠️  CLAUDE.md moflo section needs update');
        }
        return true;
      }
    }
  }

  if (updateOnly) {
    log('⚠️  CLAUDE.md has no moflo section (run without --update to add)');
    return false;
  }

  if (checkOnly) {
    log('⚠️  CLAUDE.md missing subagent protocol section');
    return false;
  }

  // Append section to end of CLAUDE.md
  const separator = content.endsWith('\n') ? '\n' : '\n\n';
  writeFileSync(claudeMdPath, content + separator + CLAUDE_MD_SECTION + '\n', 'utf-8');
  log('📝 Added subagent protocol section to CLAUDE.md');
  return true;
}

function main() {
  console.log('');
  console.log('MoFlo Project Setup');
  console.log('───────────────────');

  const projectRoot = findProjectRoot();
  if (!projectRoot) {
    log('❌ Could not find project root (no package.json with moflo dependency)');
    process.exit(1);
  }

  log(`Project: ${projectRoot}`);
  console.log('');

  // Step 1: Copy bootstrap file
  const bootstrapOk = copyBootstrap(projectRoot);

  // Step 2: Update CLAUDE.md (skip on --update, only refresh the file)
  const claudeOk = updateOnly ? true : updateClaudeMd(projectRoot);

  console.log('');
  if (checkOnly) {
    log(bootstrapOk && claudeOk ? '✅ Setup is current' : '⚠️  Setup needs attention');
  } else {
    log('✅ Done. Subagents will now follow the MoFlo bootstrap protocol.');
  }
  console.log('');
}

main();
