#!/usr/bin/env node
/**
 * MoFlo Project Setup
 *
 * Copies the subagents guidance into the consuming project and
 * adds a CLAUDE.md section so subagents automatically follow the protocol.
 *
 * Usage:
 *   flo-setup            # First-time setup
 *   flo-setup --update   # Refresh bootstrap file after moflo upgrade
 *   flo-setup --check    # Check if setup is current
 *
 * What it does:
 *   1. Copies moflo/.claude/guidance/shipped/moflo-subagents.md → project's .claude/guidance/moflo-subagents.md
 *   2. Appends a subagent protocol section to CLAUDE.md (idempotent, with markers)
 *
 * Historical note (#939): pre-fix builds renamed the destination to
 * moflo-bootstrap.md, but the launcher's stage-3 also synced the original name
 * — consumers ended up with two copies of the same content. The launcher now
 * prunes any legacy moflo-bootstrap.md on first session-start after upgrade.
 *
 * The project can layer its own guidance files on top for
 * project-specific rules (companyId, entity templates, etc.).
 *
 * The CLAUDE.md content is owned by `src/cli/init/claudemd-generator.ts` (compiled to
 * `dist/src/cli/init/claudemd-generator.js`). This script is a thin wrapper so consumers
 * always get byte-identical output regardless of which entry point they use
 * (`flo init` vs `flo-setup`).
 */

import { existsSync, readFileSync, writeFileSync, mkdirSync, copyFileSync, unlinkSync } from 'node:fs';
import { dirname, resolve, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { mofloInternalURL } from './lib/moflo-resolve.mjs';

// Resolve moflo's installed package root via Node module resolution so the script
// works identically from bin/ (canonical) or from .claude/scripts/ (synced copy).
const mofloRoot = dirname(fileURLToPath(mofloInternalURL('package.json')));

// Single source of truth: claudemd-generator.ts owns the section content,
// claudemd-injection.ts owns the marker-replace logic. Use the shared
// mofloInternalURL helper so the script works identically when invoked
// from bin/ (canonical) or from .claude/scripts/ (synced copy).
const { generateClaudeMd } = await import(mofloInternalURL('dist/src/cli/init/claudemd-generator.js'));
const { applyInjectionReplacement, computeInjectionDrift } = await import(
  mofloInternalURL('dist/src/cli/services/claudemd-injection.js')
);

const args = process.argv.slice(2);
const updateOnly = args.includes('--update');
const checkOnly = args.includes('--check');

// Canonical section content (owned by claudemd-generator.ts). Trim the trailing newline
// that generateClaudeMd appends so the marker-replace logic below stays exact.
const CLAUDE_MD_SECTION = generateClaudeMd({}).trimEnd();

function log(msg) {
  console.log(`[flo-setup] ${msg}`);
}

function findProjectRoot() {
  // Walk up from cwd looking for package.json that depends on moflo
  let dir = process.cwd();
  const root = resolve(dir, '/');

  while (dir !== root) {
    const pkgPath = join(dir, 'package.json');
    if (existsSync(pkgPath)) {
      try {
        const pkg = JSON.parse(readFileSync(pkgPath, 'utf-8'));
        const deps = { ...pkg.dependencies, ...pkg.devDependencies };
        if (deps && deps.moflo) {
          return dir;
        }
      } catch { /* ignore parse errors */ }
    }
    dir = dirname(dir);
  }

  // Fallback: use cwd if it has a package.json
  if (existsSync(join(process.cwd(), 'package.json'))) {
    return process.cwd();
  }

  return null;
}

function copySubagentsGuidance(projectRoot) {
  const shippedSource = join(mofloRoot, '.claude', 'guidance', 'shipped', 'moflo-subagents.md');
  const source = existsSync(shippedSource)
    ? shippedSource
    : join(mofloRoot, '.claude', 'guidance', 'moflo-subagents.md');
  const targetDir = join(projectRoot, '.claude', 'guidance');
  const target = join(targetDir, 'moflo-subagents.md');

  if (!existsSync(source)) {
    log('❌ Source subagents guidance not found in moflo package');
    return false;
  }

  // Read source content and prepend auto-generated notice
  const content = readFileSync(source, 'utf-8');
  const header = `<!-- AUTO-GENERATED by flo-setup. Do not edit — changes will be overwritten. -->
<!-- Source: node_modules/moflo/.claude/guidance/shipped/moflo-subagents.md -->
<!-- To customize, add project-specific guidance in .claude/guidance/. -->

`;

  mkdirSync(targetDir, { recursive: true });

  // Check if file exists and is current
  if (existsSync(target)) {
    const existing = readFileSync(target, 'utf-8');
    const newContent = header + content;
    if (existing === newContent) {
      log('✅ moflo-subagents.md is current');
      return true;
    }
    log('📝 Updating moflo-subagents.md');
  } else {
    log('📝 Creating .claude/guidance/moflo-subagents.md');
  }

  if (!checkOnly) {
    writeFileSync(target, header + content, 'utf-8');
  }
  return true;
}

// Best-effort cleanup of pre-#939 moflo-bootstrap.md left over from prior
// installs. Only removes the file if it carries one of our auto-generated
// headers — never deletes a homonymous user-authored file. Idempotent.
function cleanupLegacyBootstrap(projectRoot) {
  const legacy = join(projectRoot, '.claude', 'guidance', 'moflo-bootstrap.md');
  if (!existsSync(legacy)) return;
  try {
    const head = readFileSync(legacy, 'utf-8').slice(0, 200);
    const ours = head.includes('AUTO-GENERATED by moflo init') || head.includes('AUTO-GENERATED by flo-setup');
    if (!ours) return;
    if (!checkOnly) {
      unlinkSync(legacy);
      log('🧹 Removed legacy moflo-bootstrap.md (pre-#939 duplicate of moflo-subagents.md)');
    } else {
      log('⚠️  Legacy moflo-bootstrap.md present — will be removed on next non-check run');
    }
  } catch { /* non-fatal */ }
}

function updateClaudeMd(projectRoot) {
  const claudeMdPath = join(projectRoot, 'CLAUDE.md');
  const existed = existsSync(claudeMdPath);
  const content = existed ? readFileSync(claudeMdPath, 'utf-8') : null;

  // Single source of truth for the marker-replace logic lives in
  // src/cli/services/claudemd-injection.ts. Classify state for logging,
  // then apply (or report) the replacement.
  const report = computeInjectionDrift(content, CLAUDE_MD_SECTION);

  if (report.state === 'in-sync') {
    log('✅ CLAUDE.md moflo section is current');
    return true;
  }

  // `updateOnly` is informational — refresh the bootstrap mirror file but
  // leave CLAUDE.md alone unless an inject already exists.
  if (updateOnly) {
    if (!existed) { log('⚠️  No CLAUDE.md found'); return false; }
    if (report.state === 'no-marker') {
      log('⚠️  CLAUDE.md has no moflo section (run without --update to add)');
      return false;
    }
    // Existing block (current or legacy) + drift → fall through to write.
  }

  if (checkOnly) {
    if (!existed) { log('⚠️  No CLAUDE.md found'); return false; }
    if (report.state === 'no-marker') { log('⚠️  CLAUDE.md missing subagent protocol section'); return false; }
    log('⚠️  CLAUDE.md moflo section needs update');
    return false;
  }

  const result = applyInjectionReplacement(content, CLAUDE_MD_SECTION);
  if (!result.changed) return true;
  writeFileSync(claudeMdPath, result.contents, 'utf-8');

  switch (report.state) {
    case 'no-file':       log('📝 Creating CLAUDE.md with subagent protocol section'); break;
    case 'no-marker':     log('📝 Added subagent protocol section to CLAUDE.md'); break;
    case 'legacy-marker': log('📝 Replaced legacy CLAUDE.md section with minimal moflo injection'); break;
    case 'drifted':       log('📝 Updated CLAUDE.md moflo section'); break;
  }
  return true;
}

function main() {
  console.log('');
  console.log('MoFlo Project Setup');
  console.log('───────────────────');

  const projectRoot = findProjectRoot();
  if (!projectRoot) {
    log('❌ Could not find project root (no package.json with moflo dependency)');
    process.exit(1);
  }

  log(`Project: ${projectRoot}`);
  console.log('');

  // Step 1: Copy subagents guidance under its real name (#939 — was moflo-bootstrap.md)
  const bootstrapOk = copySubagentsGuidance(projectRoot);

  // Step 1b: Remove pre-#939 moflo-bootstrap.md if it still exists from an older install
  cleanupLegacyBootstrap(projectRoot);

  // Step 2: Update CLAUDE.md (skip on --update, only refresh the file)
  const claudeOk = updateOnly ? true : updateClaudeMd(projectRoot);

  console.log('');
  if (checkOnly) {
    log(bootstrapOk && claudeOk ? '✅ Setup is current' : '⚠️  Setup needs attention');
  } else {
    log('✅ Done. Subagents will now follow the MoFlo bootstrap protocol.');
  }
  console.log('');
}

main();
