#!/usr/bin/env node
/**
 * Sync root package.json version → src/cli/version.ts.
 * Run automatically as part of `npm run build`.
 */
import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');

const rootPkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf-8'));
const version = rootPkg.version;

const versionTs = `/**
 * Auto-generated by build. Do not edit manually.
 * Source of truth: root package.json → scripts/sync-version.mjs
 */
export const VERSION = '${version}';
`;
writeFileSync(join(root, 'src/cli/version.ts'), versionTs);

console.log(`✓ Version synced: ${version}`);
