#!/usr/bin/env node
/**
 * Sync root package.json version → CLI version.ts and CLI package.json.
 * Run automatically as part of `npm run build`.
 */
import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');

const rootPkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf-8'));
const version = rootPkg.version;

// 1. Update version.ts (used at runtime)
const versionTs = `/**
 * Auto-generated by build. Do not edit manually.
 * Source of truth: root package.json → scripts/sync-version.mjs
 */
export const VERSION = '${version}';
`;
writeFileSync(join(root, 'src/packages/cli/src/version.ts'), versionTs);

// 2. Update CLI sub-package.json (for consistency)
const cliPkgPath = join(root, 'src/packages/cli/package.json');
const cliPkg = JSON.parse(readFileSync(cliPkgPath, 'utf-8'));
if (cliPkg.version !== version) {
  cliPkg.version = version;
  writeFileSync(cliPkgPath, JSON.stringify(cliPkg, null, 2) + '\n');
}

console.log(`✓ Version synced: ${version}`);
